function P = nl_params()
% Parameter struct of the nonlinear Navion model, built from the navion_params script.

navion_params;

P = struct('h_init', h_init, 'V0', V0, 'alpha0', alpha0, 'Theta0', Theta0, 'rho0', rho0, 'M0', M0, 'g', g, ...
    'S', S, 'c', c, 'b', b, 'm', m, 'Ixx', Ixx, 'Iyy', Iyy, 'Izz', Izz, 'Ixz', Ixz, ...
    'CL0', CL0, 'CLalpha', CLalpha, 'CLq', CLq, 'CLeta', CLeta, ...
    'CD0', CD0, 'CDalpha', CDalpha, 'CDq', CDq, 'CDeta', CDeta, ...
    'Cmalpha', Cmalpha, 'Cmq', Cmq, 'Cmeta', Cmeta, ...
    'dCL_dM', dCL_dM, 'dCD_dM', dCD_dM, 'dCm_dM', dCm_dM, ...
    'CYbeta', CYbeta, 'CYp', CYp, 'CYr', CYr, ...
    'Clbeta', Clbeta, 'Clp', Clp, 'Clr', Clr, ...
    'Cnbeta', Cnbeta, 'Cnp', Cnp, 'Cnr', Cnr, ...
    'CYxi', CYxi, 'Clxi', Clxi, 'Cnxi', Cnxi, ...
    'CYzeta', CYzeta, 'Clzeta', Clzeta, 'Cnzeta', Cnzeta);
end
