function nl_setup()
% Model initialization: trims at V0 and h_init, assigns nl_x0 (12-state initial
% condition) in the base workspace, and writes the generated file
% src/nonlinear/nl_const.m next to this file (constants for the MATLAB Function blocks).
% Optional base-workspace overrides: nl_h0 (start altitude), nl_dx0 (initial state offset).

P = nl_params();
h0 = P.h_init;
if evalin('base', 'exist(''nl_h0'', ''var'')'), h0 = evalin('base', 'nl_h0'); end

[x0, u0, tr] = trim_navion(P, P.V0, h0);
if evalin('base', 'exist(''nl_dx0'', ''var'')'), x0 = x0 + evalin('base', 'nl_dx0'); end   % optional initial state offset
P.eta0 = u0(1);  P.T0 = u0(4);
P.alpha_tr = tr.alpha;  P.theta_tr = x0(8);

txt = sprintf('function P = nl_const()\n%% generated by nl_setup.m - do not edit\n');
fn = fieldnames(P);
for k = 1:numel(fn)
    txt = [txt sprintf('P.%s = %.17g;\n', fn{k}, P.(fn{k}))]; %#ok<AGROW>
end
txt = [txt sprintf('end\n')];

cfile = fullfile(fileparts(mfilename('fullpath')), 'nl_const.m');
old = '';
if exist(cfile, 'file') == 2, old = fileread(cfile); end
if ~strcmp(old, txt)
    fid = fopen(cfile, 'w');  fwrite(fid, txt);  fclose(fid);
    rehash;
end

assignin('base', 'nl_x0', x0);
fprintf('nl_setup: trim V=%.2f m/s h=%.0f m  alpha=%.4f rad  eta=%.5f  T=%.1f N (residual %.1e)\n', ...
    P.V0, h0, tr.alpha, tr.eta, tr.T, tr.residual);
end
